# 0. Summary
- Download complete reference sites data (9254).
- Drop useless columns : 
    - dates, 
    - geometrie,
    - loi stat (statique? statistique?)
    - [...].
- Track non-pertinent sites -> not found.
- Save to LOCAL_DATA_DIRECTORY as "hubeau_{HUBEAU_DATA_ENDPOINT}_1.csv".

In [1]:
import os
import pandas

# LOCAL COMPONENTS:
from config import HUBEAU_BASE_URL, LOCAL_DATA_DIRECTORY
from utils import request_json_all, save_dataframe_as_csv

SyntaxError: Non-UTF-8 code starting with '\xe9' on line 18, but no encoding declared; see https://peps.python.org/pep-0263/ for details (config.py, line 18)

# 1. Download data

In [2]:
HUBEAU_DATA_ENDPOINT = "referentiel/sites"

In [3]:
url = f"{HUBEAU_BASE_URL}/{HUBEAU_DATA_ENDPOINT}"
params = {"size": 200}  
results = request_json_all(url, params=params, timeout_in_seconds=60)

>>> page 001: 200 records / 9254 at rate 0.8220844774008976 requests / second
>>> page 002: 200 records / 9254 at rate 0.7927510840871075 requests / second
>>> page 003: 200 records / 9254 at rate 1.0216737877329671 requests / second
>>> page 004: 200 records / 9254 at rate 0.8998235446029034 requests / second
>>> page 005: 200 records / 9254 at rate 0.8260482759133408 requests / second
>>> page 006: 200 records / 9254 at rate 0.9364570209928692 requests / second
>>> page 007: 200 records / 9254 at rate 1.0477741609611622 requests / second
>>> page 008: 200 records / 9254 at rate 1.1534136791690461 requests / second
>>> page 009: 200 records / 9254 at rate 1.2495257008693783 requests / second
>>> page 010: 200 records / 9254 at rate 1.3406531206181589 requests / second
>>> page 011: 200 records / 9254 at rate 1.4236299535366008 requests / second
>>> page 012: 200 records / 9254 at rate 1.50465106452182 requests / second
>>> page 013: 200 records / 9254 at rate 1.5646790789047198 requests / second
>>> page 014: 200 records / 9254 at rate 1.6306434239411998 requests / second
>>> page 015: 200 records / 9254 at rate 1.6919195052376188 requests / second
>>> page 016: 200 records / 9254 at rate 1.7499443298960051 requests / second
>>> page 017: 200 records / 9254 at rate 1.806908832839994 requests / second
>>> page 018: 200 records / 9254 at rate 1.864839345126439 requests / second
>>> page 019: 200 records / 9254 at rate 1.9150227791959582 requests / second
>>> page 020: 200 records / 9254 at rate 1.9589118244815003 requests / second
>>> page 021: 200 records / 9254 at rate 2.0062010719801058 requests / second
>>> page 022: 200 records / 9254 at rate 2.0396952509868185 requests / second
>>> page 023: 200 records / 9254 at rate 2.0765340011225923 requests / second
>>> page 024: 200 records / 9254 at rate 2.1142097889851255 requests / second
>>> page 025: 200 records / 9254 at rate 2.1499977769022984 requests / second
>>> page 026: 200 records / 9254 at rate 2.184144371942985 requests / second
>>> page 027: 200 records / 9254 at rate 2.218558040806184 requests / second
>>> page 028: 200 records / 9254 at rate 2.251153655949915 requests / second
>>> page 029: 200 records / 9254 at rate 2.2769036779453216 requests / second
>>> page 030: 200 records / 9254 at rate 2.308664610672571 requests / second
>>> page 031: 200 records / 9254 at rate 2.3393719314609296 requests / second
>>> page 032: 200 records / 9254 at rate 2.3671013157828544 requests / second
>>> page 033: 200 records / 9254 at rate 2.3888640712454814 requests / second
>>> page 034: 200 records / 9254 at rate 2.4072788749737937 requests / second
>>> page 035: 200 records / 9254 at rate 2.4304426412411804 requests / second
>>> page 036: 200 records / 9254 at rate 2.454373369503524 requests / second
>>> page 037: 200 records / 9254 at rate 2.4754245537093866 requests / second
>>> page 038: 200 records / 9254 at rate 2.496071643036531 requests / second
>>> page 039: 200 records / 9254 at rate 2.511149018729887 requests / second
>>> page 040: 200 records / 9254 at rate 2.528289345523227 requests / second
>>> page 041: 200 records / 9254 at rate 2.5487319095205136 requests / second
>>> page 042: 200 records / 9254 at rate 2.566496237058213 requests / second
>>> page 043: 200 records / 9254 at rate 2.5855154733179906 requests / second
>>> page 044: 200 records / 9254 at rate 2.6013346975363105 requests / second
>>> page 045: 200 records / 9254 at rate 2.6203245766938426 requests / second
>>> page 046: 200 records / 9254 at rate 2.6359909145415754 requests / second
>>> page 047: 54 records / 9254 at rate 2.6510378023325294 requests / second

In [9]:
print(type(results), results.keys())
assert(all(key in results.keys() for key in ("api_version", "count", "data")))
data = results["data"]
print(type(data), len(data))
assert(isinstance(data, list))
assert(len(data) > 0)
data_0 = data[0]
print(type(data_0), data_0.keys())

<class 'dict'> dict_keys(['api_version', 'count', 'data'])
<class 'list'> 9254
<class 'dict'> dict_keys(['code_site', 'libelle_site', 'type_site', 'coordonnee_x_site', 'coordonnee_y_site', 'code_projection', 'longitude_site', 'latitude_site', 'altitude_site', 'code_systeme_alti_site', 'surface_bv', 'statut_site', 'premier_mois_etiage_site', 'premier_mois_annee_hydro_site', 'influence_generale_site', 'code_entite_hydro_site', 'code_troncon_hydro_site', 'code_commune_site', 'code_zone_hydro_site', 'libelle_commune', 'code_departement', 'code_region', 'libelle_region', 'code_cours_eau', 'libelle_cours_eau', 'uri_cours_eau', 'grandeur_hydro', 'date_maj_site', 'date_premiere_donnee_dispo_site', 'commentaire_influence_generale_site', 'commentaire_site', 'type_contexte_loi_stat_site', 'type_loi_site', 'libelle_departement', 'geometry'])

In [10]:
df = pandas.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9254 entries, 0 to 9253
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   code_site                            9254 non-null   str
 1   libelle_site                         9254 non-null   str
 2   type_site                            9254 non-null   str
 3   coordonnee_x_site                    9254 non-null   float64
 4   coordonnee_y_site                    9254 non-null   float64
 5   code_projection                      9254 non-null   int64
 6   longitude_site                       9254 non-null   float64
 7   latitude_site                        9254 non-null   float64
 8   altitude_site                        4475 non-null   float64
 9   code_systeme_alti_site               4475 non-null   float64
 10  surface_bv                           4477 non-null   float64
 11  statut_site                          9252 non-null   float64
 12  premier_mois_etiage_site             9254 non-null   int64
 13  premier_mois_annee_hydro_site        9254 non-null   int64
 14  influence_generale_site              5881 non-null   float64
 15  code_entite_hydro_site               9252 non-null   str
 16  code_troncon_hydro_site              9253 non-null   str
 17  code_commune_site                    9251 non-null   object
 18  code_zone_hydro_site                 9252 non-null   str
 19  libelle_commune                      9211 non-null   object
 20  code_departement                     9211 non-null   object
 21  code_region                          9211 non-null   object
 22  libelle_region                       9211 non-null   object
 23  code_cours_eau                       9252 non-null   str
 24  libelle_cours_eau                    8474 non-null   str
 25  uri_cours_eau                        9252 non-null   str
 26  grandeur_hydro                       9254 non-null   str
 27  date_maj_site                        9252 non-null   str
 28  date_premiere_donnee_dispo_site      0 non-null      object
 29  commentaire_influence_generale_site  668 non-null    str
 30  commentaire_site                     4691 non-null   str
 31  type_contexte_loi_stat_site          3883 non-null   object
 32  type_loi_site                        3883 non-null   object
 33  libelle_departement                  9211 non-null   object
 34  geometry                             9254 non-null   object
dtypes: float64(9), int64(3), object(10), str(13)
memory usage: 4.2+ MB

In [25]:
display(df.head())

,code_site,libelle_site,type_site,coordonnee_x_site,coordonnee_y_site,code_projection,longitude_site,latitude_site,altitude_site,code_systeme_alti_site,...,libelle_region,code_cours_eau,libelle_cours_eau,uri_cours_eau,grandeur_hydro,commentaire_influence_generale_site,commentaire_site,type_contexte_loi_stat_site,type_loi_site,libelle_departement
0,10110001,La Grande Rivière à Goyaves à Petit-Bourg [Bar...,STANDARD,643352.000,1790354.000,39,-61.658990,16.189402,133.81,11.0,...,[GUADELOUPE],10--0020,Grande Rivière à Goyaves,http://id.eaufrance.fr/CEA/10--0020,Q,NaN,NaN,None,None,[GUADELOUPE]
1,10110002,[Grande riviere a goyave] à Petit-Bourg [canal...,STANDARD,644100.000,1791070.000,39,-61.651950,16.195829,NaN,NaN,...,[GUADELOUPE],00000000,NaN,http://id.eaufrance.fr/CEA/00000000,Q,NaN,NaN,None,None,[GUADELOUPE]
2,10110003,[La Grande Rivière à Goyaves à Petit-Bourg-Bar...,STANDARD,643710.000,1790860.000,39,-61.655610,16.193954,NaN,NaN,...,[GUADELOUPE],1---0002,NaN,http://id.eaufrance.fr/CEA/1---0002,Q,NaN,NaN,None,None,[GUADELOUPE]
3,10110004,La Grande Rivière à Goyaves à Petit-Bourg [Ver...,STANDARD,641900.000,1786900.000,39,-61.672778,16.158271,NaN,NaN,...,[GUADELOUPE],10--0020,Grande Rivière à Goyaves,http://id.eaufrance.fr/CEA/10--0020,Q,NaN,NaN,None,None,[GUADELOUPE]
4,10150001,La rivière Bras David à Petit-Bourg [Maison Fo...,STANDARD,639703.869,1788847.318,39,-61.693200,16.175998,214.38,11.0,...,[GUADELOUPE],101-1020,Rivière Bras David,http://id.eaufrance.fr/CEA/101-1020,Q,NaN,NaN,None,None,[GUADELOUPE]

# 2. Explore and prune columns

In [ ]:
# drop update dates
df.drop(columns=["date_maj_site"], inplace=True)
df.drop(columns=["date_premiere_donnee_dispo_site"], inplace=True)

In [ ]:
df.drop(columns=["grandeur_hydro"], inplace=True)  # unused (check the quantities availability at station-level)

In [ ]:
df.drop(columns=["geometry"], inplace=True)

In [ ]:
df.drop(columns=["type_loi_site"], inplace=True) 
df.drop(columns=["type_contexte_loi_stat_site"], inplace=True)

In [ ]:
df.drop(columns=["premier_mois_etiage_site"], inplace=True)
df.drop(columns=["premier_mois_annee_hydro_site"], inplace=True)

In [42]:

df.drop(columns=["surface_bv"], inplace=True)

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9254 entries, 0 to 9253
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   code_site                            9254 non-null   str
 1   libelle_site                         9254 non-null   str
 2   type_site                            9254 non-null   str
 3   coordonnee_x_site                    9254 non-null   float64
 4   coordonnee_y_site                    9254 non-null   float64
 5   code_projection                      9254 non-null   int64
 6   longitude_site                       9254 non-null   float64
 7   latitude_site                        9254 non-null   float64
 8   altitude_site                        4475 non-null   float64
 9   code_systeme_alti_site               4475 non-null   float64
 10  statut_site                          9252 non-null   float64
 11  influence_generale_site              5881 non-null   float64
 12  code_entite_hydro_site               9252 non-null   str
 13  code_troncon_hydro_site              9253 non-null   str
 14  code_commune_site                    9251 non-null   object
 15  code_zone_hydro_site                 9252 non-null   str
 16  libelle_commune                      9211 non-null   object
 17  code_departement                     9211 non-null   object
 18  code_region                          9211 non-null   object
 19  libelle_region                       9211 non-null   object
 20  code_cours_eau                       9252 non-null   str
 21  libelle_cours_eau                    8474 non-null   str
 22  uri_cours_eau                        9252 non-null   str
 23  commentaire_influence_generale_site  668 non-null    str
 24  commentaire_site                     4691 non-null   str
 25  libelle_departement                  9211 non-null   object
dtypes: float64(8), int64(1), object(6), str(11)
memory usage: 3.3+ MB

In [29]:
display(df["commentaire_influence_generale_site"].value_counts())
display(df["commentaire_site"].value_counts())

commentaire_influence_generale_site
Attention: il s'agit d'un débit naturel reconstitué (QNR)                                                                                                                            25
Ouvrage de prise                                                                                                                                                                     10
Herbiers.                                                                                                                                                                             7
En étiage, les débits des canaux sont fortement influencés par les transferts d'eau.                                                                                                  6
Barrage de Villerest.                                                                                                                                                                 6
                                                                                                                                                                                     ..
Prise d'eau EDF de Sovenzia sur Tavignano amont                                                                                                                                       1
Prise d';eau tête de bassin (Sovenzia) vers bassin versant Golo (6 m3/s max) micro-centrale Cardiccia à 3km amont                                                                     1
Pompages amont                                                                                                                                                                        1
influence étiage limitée                                                                                                                                                              1
Existence d'une prise d'eau exploitée par l'Office d’Équipement Hydraulique de la Corse qui alimente le lac situé un km à l'amont du site. Le prélèvement maximal est de 600 L/s.     1
Name: count, Length: 559, dtype: int64

commentaire_site
Point de mesure ONDE (Observatoire National Des Etiages)                                                                                                                                                                                                                                                                                                                                                                                  3245
Mise à jour de la "Surface de bassin versant topographique" - Juin 2023 - Source BNBV                                                                                                                                                                                                                                                                                                                                                      127
Point de mesure ONDE (Observatoire National Des Etiages) jusqu'à l'automne 2016                                                                                                                                                                                                                                                                                                                                                             62
Le régime hydrologique est de type pluvial.                                                                                                                                                                                                                                                                                                                                                                                                 55
Le régime hydrologique est de type pluvial.                                                                                                                                                                                                                                                                                                                                                                                                 50
                                                                                                                                                                                                                                                                                                                                                                                                                                          ...
Ce site est également un point de mesure ONDE (Observatoire National Des Etiages) au pont de Purcilella                                                                                                                                                                                                                                                                                                                                      1
Influencée à partir de 1976 par la dérivation de l'Asinao (Haut-Rizzanèse) et 1979 par la restitution issue de la retenue de l'Ospedale. Ce site est également un point de mesure ONDE (Observatoire National Des Etiages)                                                                                                                                                                                                                   1
Pour la station de 1971 à 1997 : Station d'étude perturbée en étiage par des pompages amont et un infero-flux important. Le cours conflue avec le Petroso contrôlé par la station S.R.A.E. du pont de Bala. Critique et homogénéisation des courbes de tarage. Recalcul de toute la chronique des QMJ de 1974 à 1996 en décembre 1999. Attention, les années 1971 à 1973, non traitées, doivent être considérées comme très douteuses.       1
Pour l'ancienne station en fonctionnement de 1971 à 1989 : Station d'étude perturbée en étiage par des pompages amont et un infero-flux important. Ce cours d'eau est un affluent du Stabiaccio contrôlé par la station S.R.A.E. du Moulin de Lastreto.  Une nouvelle station a été créée en 2020 au pont de Bala, suite aux études d'enjeux et à l'expertise des sites menées en 2018.                                                      1
Station d'étude sur petit cours d'eau temporaire.                                                                                                                                                                                                                                                                                                                                                                                            1
Name: count, Length: 794, dtype: int64

In [38]:
display(df["influence_generale_site"].value_counts())

influence_generale_site
1.0    2973
0.0    1088
2.0    1069
3.0     698
4.0      53
Name: count, dtype: int64

In [32]:
display(df["libelle_site"].value_counts())
display(df["libelle_commune"].value_counts())
display(df["libelle_departement"].value_counts())
display(df["libelle_region"].value_counts())

libelle_site
L'Yerres à Yerres                                           3
Le Donozau à Naussac                                        3
Le Trèvezel à Trèves                                        3
L'Antenne aux Touches-de-Périgny                            3
L'Antenne à Prignac                                         3
                                                           ..
Le ruisseau de Palavesani à Porto-Vecchio                   1
Le Bala à Porto-Vecchio                                     1
Le ruisseau de Francolu à Bonifacio                         1
Le ruisseau de Ventilegne à Figari                          1
[Océan] à Saint-Pierre-d'Oléron [l'Océan à la Cotinière]    1
Name: count, Length: 8994, dtype: int64

libelle_commune
[LAMENTIN]                 17
[PETIT-BOURG]              12
[AJACCIO]                  12
[CAPESTERRE-BELLE-EAU]     11
[SAINT-JOSEPH]             10
                           ..
[LECCI]                     1
[PORTO-VECCHIO]             1
[BONIFACIO]                 1
[FIGARI]                    1
[SAINT-PIERRE-D'OLERON]     1
Name: count, Length: 6945, dtype: int64

libelle_departement
[GARD]                              227
[VIENNE]                            178
[CHARENTE]                          161
[CHARENTE-MARITIME]                 159
[ALPES-MARITIMES]                   159
                                   ...
[ARIEGE, HAUTE-GARONNE]               1
[TARN, TARN-ET-GARONNE]               1
[CHARENTE, CHARENTE-MARITIME]         1
[CHARENTE-MARITIME, DEUX-SEVRES]      1
[ISERE, SAVOIE]                       1
Name: count, Length: 116, dtype: int64

libelle_region
[OCCITANIE]                             1620
[NOUVELLE-AQUITAINE]                    1277
[AUVERGNE-RHONE-ALPES]                  1220
[GRAND EST]                              850
[BOURGOGNE-FRANCHE-COMTE]                686
[PROVENCE-ALPES-COTE D'AZUR]             591
[CENTRE-VAL DE LOIRE]                    579
[BRETAGNE]                               475
[NORMANDIE]                              466
[HAUTS-DE-FRANCE]                        442
[PAYS DE LA LOIRE]                       396
[ILE-DE-FRANCE]                          232
[CORSE]                                  109
[MARTINIQUE]                              82
[GUADELOUPE]                              59
[LA REUNION]                              59
[GUYANE]                                  41
[MAYOTTE]                                 22
[BRETAGNE, PAYS DE LA LOIRE]               3
[BOURGOGNE-FRANCHE-COMTE, GRAND EST]       1
[NORMANDIE, PAYS DE LA LOIRE]              1
Name: count, dtype: int64

In [35]:
display(df[df["libelle_site"] == "L'Yerres à Yerres"])

,code_site,libelle_site,type_site,coordonnee_x_site,coordonnee_y_site,code_projection,longitude_site,latitude_site,altitude_site,code_systeme_alti_site,...,libelle_commune,code_departement,code_region,libelle_region,code_cours_eau,libelle_cours_eau,uri_cours_eau,commentaire_influence_generale_site,commentaire_site,libelle_departement
1436,F4870001,L'Yerres à Yerres,STANDARD,661649.000000,6.846251e+06,26,2.478730,48.715255,NaN,NaN,...,[YERRES],[91],[11],[ILE-DE-FRANCE],F4--0210,L'Yerres,http://id.eaufrance.fr/CEA/F4--0210,NaN,NaN,[ESSONNE]
1441,F4870008,L'Yerres à Yerres,STANDARD,662829.900000,6.845847e+06,26,2.494816,48.711687,NaN,NaN,...,[YERRES],[91],[11],[ILE-DE-FRANCE],F4--0210,L'Yerres,http://id.eaufrance.fr/CEA/F4--0210,Barrages,NaN,[ESSONNE]
1443,F4870010,L'Yerres à Yerres,STANDARD,662991.853103,6.845423e+06,26,2.497053,48.707885,NaN,NaN,...,[YERRES],[91],[11],[ILE-DE-FRANCE],F4870801,L'Yerres,http://id.eaufrance.fr/CEA/F4870801,NaN,NaN,[ESSONNE]

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9254 entries, 0 to 9253
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   code_site                            9254 non-null   str
 1   libelle_site                         9254 non-null   str
 2   type_site                            9254 non-null   str
 3   coordonnee_x_site                    9254 non-null   float64
 4   coordonnee_y_site                    9254 non-null   float64
 5   code_projection                      9254 non-null   int64
 6   longitude_site                       9254 non-null   float64
 7   latitude_site                        9254 non-null   float64
 8   altitude_site                        4475 non-null   float64
 9   code_systeme_alti_site               4475 non-null   float64
 10  statut_site                          9252 non-null   float64
 11  influence_generale_site              5881 non-null   float64
 12  code_entite_hydro_site               9252 non-null   str
 13  code_troncon_hydro_site              9253 non-null   str
 14  code_commune_site                    9251 non-null   object
 15  code_zone_hydro_site                 9252 non-null   str
 16  libelle_commune                      9211 non-null   object
 17  code_departement                     9211 non-null   object
 18  code_region                          9211 non-null   object
 19  libelle_region                       9211 non-null   object
 20  code_cours_eau                       9252 non-null   str
 21  libelle_cours_eau                    8474 non-null   str
 22  uri_cours_eau                        9252 non-null   str
 23  commentaire_influence_generale_site  668 non-null    str
 24  commentaire_site                     4691 non-null   str
 25  libelle_departement                  9211 non-null   object
dtypes: float64(8), int64(1), object(6), str(11)
memory usage: 3.3+ MB

# 10. Save the dataframe

In [44]:
display(df.describe())

,coordonnee_x_site,coordonnee_y_site,code_projection,longitude_site,latitude_site,altitude_site,code_systeme_alti_site,statut_site,influence_generale_site
count,9.254000e+03,9.254000e+03,9254.000000,9254.000000,9254.000000,4.475000e+03,4475.000000,9252.000000,5881.000000
mean,6.650331e+05,6.406611e+06,26.193862,2.224842,44.772916,5.679407e+02,2.632402,1.088305,1.261180
std,3.222784e+05,1.019972e+06,3.016046,10.918863,8.621636,1.556667e+04,2.050126,0.311015,0.924425
min,-6.380454e+06,4.241740e+01,5.000000,-61.790584,-21.381010,-9.990000e+02,0.000000,1.000000,0.000000
25%,5.011122e+05,6.345124e+06,26.000000,0.409788,44.177687,6.000000e+01,2.000000,1.000000,1.000000
50%,6.670429e+05,6.566504e+06,26.000000,2.632133,46.132514,1.710000e+02,3.000000,1.000000,1.000000
75%,8.475438e+05,6.785138e+06,26.000000,5.082925,48.057723,3.425000e+02,3.000000,1.000000,2.000000
max,7.743604e+06,8.594348e+06,52.000000,55.721977,50.954672,1.020000e+06,28.000000,3.000000,4.000000

In [49]:
endpoint = HUBEAU_DATA_ENDPOINT.replace("/","_")
base_name = f"hubeau_{endpoint}_1"
filepath = save_dataframe_as_csv(df, base_name=base_name, output_dirpath=LOCAL_DATA_DIRECTORY)

In [50]:
filesize_in_kb = os.path.getsize(filepath) / 1024
print(f">>> saved : \"{filepath}\" ({len(df)} records, {filesize_in_kb:.0f} Kb)")

>>> saved : "c:\Users\nicolas\Repositories\Jedha\Shares\M11\ml-flood-forecasting\eda\data\hubeau\hubeau_referentiel_sites_1.csv" (9254 records, 2874 Kb)